---
kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: test
  image: golang:1.12.7
  commands:
  - go test -tags "sqlite integration" -v -cover ./...

- name: build
  image: golang:1.12.7
  commands:
  - CGO_ENABLED=0 GOOS=linux go build -tags "mysql" -a -installsuffix cgo -o tabemap-api .

- name: docker
  image: plugins/docker
  settings:
    repo: docker.io/kanatakita/tabemap-api
    tags: latest
    dockerfile: ./kubernetes/container/Dockerfile
    username:
      from_secret: docker-username
    password:
      from_secret: docker-password
  depends_on:
  - test
  - build
