apiVersion: skaffold/v1beta12
kind: Config
build:
  artifacts:
  - imageName: docker.io/kanatakita/tabemap-api
    workspace: .
    docker:
      dockerfilePath: ./kubernetes/container/Dockerfile
  tagPolicy:
    gitCommit:
      variant: Tags
    envTemplate:
      template: latest
deploy:
  kubectl:
    manifests:
      - ./kubernetes/manifest/manifest.yaml
